config/routes.rb
HackathonTeams::Application.routes.draw do
  root 'pages#root'

  resources :representatives
  resources :sponsors
  resources :teams
  resources :schools
  resources :hackers

  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}

  get 'committed' => 'hackers#committed'

  post 'update_commit/:id' => 'hackers#update_commit'

  get 'stats' => 'stats#index'
end

app/models/hacker.rb
class Hacker < ActiveRecord::Base
  belongs_to :school
  belongs_to :team
  belongs_to :status
  has_many :ratings

  has_attached_file :resume,
    :storage => :s3,
    :s3_credentials => {
      :bucket => ENV['AWS_BUCKET'],
      :access_key_id => ENV['AWS_ACCESS_KEY_ID'],
      :secret_access_key => ENV['AWS_SECRET_ACCESS_KEY']
    }
  validates_format_of :resume_file_name,
                      :with => %r{\.(docx|doc|pdf)\z}i,
                      :allow_blank => true
end

app/controllers/hackers_controller.rb
class HackersController < ApplicationController
  before_filter :cancan_hack
  before_filter :prepare_schools, :prepare_teams, :prepare_statuses, :prepare_tshirts
  before_action :authenticate_user!, :except => [:commit, :committed, :update, :update_commit]
  before_action :set_hacker, only: [:show, :edit, :update, :destroy, :update_commit]
  helper_method :sort_column, :sort_direction
  load_and_authorize_resource

  # GET /hackers
  # GET /hackers.json
  def index
    @hackers = Hacker.accessible_by(current_ability)
               .order(sort_column + " " + sort_direction)
               .paginate(:page => params[:page], :per_page => 200)
  end

  # GET /hackers/1
  # GET /hackers/1.json
  def show
    @teammates = @hacker.team.members.split(', ').map do |teammate|
      fname, lname = teammate.split ' '
      view_context.link_to teammate, Hacker.find_by_fname_and_lname(fname, lname)
    end.join(', ').html_safe
  end

  def commit
  end

  def committed
    @hacker = Hacker.find_by_email(params[:email].downcase)

    respond_to do |format|
      if @hacker.nil? || (@hacker.status.name != 'Accepted' && @hacker.status.name != 'Committed')
        flash[:notice] = "You entered an invalid email."
        format.html { redirect_to controller: 'pages', action: 'root' }
      else
        format.html { render action: 'committed', email: @hacker.email }
      end
    end
  end

  def update_commit
    respond_to do |format|
      if @hacker.update(hacker_params)
        @hacker.status_id = Status.find_by_name('Committed').id
        @hacker.save
        flash[:notice] = "You have successfully committed to attending BoilerMake!"
        format.html { redirect_to action: 'committed', email: @hacker.email }
      else
        flash[:alert] = "There was an error with your commitment to BoilerMake. Please make sure to upload your resume as a PDF. If problems persist email - kirby@purdue.edu."
        format.html { redirect_to action: 'committed', email: @hacker.email }
      end
    end
  end

  # GET /hackers/new
  def new
    @hacker = Hacker.new
  end

  # GET /hackers/1/edit
  def edit
  end

  # POST /hackers
  # POST /hackers.json
  def create
    @hacker = Hacker.new(hacker_params)
    authorize! :create, @hacker

    unless params[:team_id]
      team = Team.create
    end

    @hacker.team_id = team.id

    respond_to do |format|
      if @hacker.save
        format.html { redirect_to @hacker, notice: 'Hacker was successfully created.' }
        format.json { render action: 'show', status: :created, location: @hacker }
      else
        format.html { render action: 'new' }
        format.json { render json: @hacker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hackers/1
  # PATCH/PUT /hackers/1.json
  def update
    respond_to do |format|
      if @hacker.update(hacker_params)
        format.html { redirect_to @hacker, notice: 'Hacker was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @hacker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hackers/1
  # DELETE /hackers/1.json
  def destroy
    @hacker.destroy
    respond_to do |format|
      format.html { redirect_to hackers_url }
      format.json { head :no_content }
    end
  end

  private
    def cancan_hack
      return if request.get?
      resource = controller_name.singularize.to_sym
      method = "#{resource}_params"
      params[resource] &&= send(method) if respond_to?(method, true)
    end

    def prepare_schools
      @schools = School.all
    end

    def prepare_teams
      @teams = Team.all
    end

    def prepare_statuses
      @statuses = Status.all
    end

    def prepare_tshirts
      @tshirts = ['XS', 'Small', 'Medium', 'Large', 'XL', 'XXL', '3XL']
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_hacker
      @hacker = Hacker.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hacker_params
      params.require(:hacker).permit(:fname, :lname, :school, :school_id,
                                     :team, :team_id, :contact_date, :status,
                                     :status_id, :email, :github, :tshirt_size,
                                     :why, :resume, :cell, :rating)
    end

    def sort_column
      Hacker.column_names.include?(params[:sort]) ? params[:sort] : "id"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
end

app/helpers/hackers_helper.rb
module HackersHelper
end

app/views/hackers/_commit.html.erb
<div class="index-carousel">
  <div class="carousel-images">
    <div class="carousel-item index-carousel-item mlb-victis active">
      <div class="index-carousel-item-wrapper">
        <section class="index-carousel-content">
          <%= form_tag({controller: "hackers", action: "committed"}, method: "get", class: "nifty_form") do %>
            <div class="panel panel-default">
              <div class="panel-heading">
                <h3>Congratulations, you've been accepted to <%= t :hackathon_name %>!</h3>
              </div>
              <div class="panel-body">
                <% if notice %>
                  <p class="alert alert-danger"><%= notice %></p>
                <% end %>
                <div class="email-text">
                  Please enter the email you used to apply.
                </div>
                <div class="form-group">
                  <div class="input-group">
                    <%= label_tag :email, "Email:", :class => 'left email-label' %>
                    <%= text_field_tag :email, nil, :class => 'form-control email-btn', :required => true %>
                    <div class="input-group-btn">
                      <%= submit_tag "Submit", class: "btn btn-primary dropdown-toggle" %>
                    </div><!-- /btn-group -->
                  </div><!-- /input-group -->
                </div>
              </div>
            </div>
          <% end %>
        </section>
        <div class="index-carousel-overlay"></div>
        <div class="index-carousel-background">
          <%= image_tag("corec2.jpg") %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/hackers/_form.html.erb
<div class="panel panel-default col-md-8 col-md-offset-2">
  <%= form_for(@hacker) do |f| %>
    <% if @hacker.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@hacker.errors.count, "error") %> prohibited this hacker from being saved:</h2>

        <ul>
        <% @hacker.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="form">
      <div class="panel-heading">
        <h3> <%= params[:action] == 'edit' ? "Editing" : "New" %> <%= link_to 'Back', @hacker, :class => 'btn btn-default' %></h3>
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="form-group col-xs-6">
            <%= f.label :First %>
            <%= f.text_field :fname, class: 'form-control' %>
          </div>
          <div class="form-group col-xs-6">
            <%= f.label :Last %>
            <%= f.text_field :lname, class: 'form-control' %>
          </div>
        </div>
        <div class="row">
          <div class="form-group col-xs-6">
            <%= f.label :email %>
            <%= f.text_field :email, class: 'form-control' %>
          </div>
          <div class="form-group col-xs-6">
            <%= f.label :school %>
            <%= f.collection_select :school_id, @schools, :id, :name, {:include_blank => "Please select"}, class: 'form-control' %>
          </div>
        </div>
        <div class="row">
          <div class="form-group col-xs-6">
            <%= f.label :rating %>
            <%= f.text_field :rating, class: 'form-control' %>
          </div>
          <div class="form-group col-xs-6">
            <%= f.label :github %>
            <%= f.text_field :github, class: 'form-control' %>
          </div>
        </div>
        <div class="row">
          <div class="form-group col-xs-6">
            <%= f.label :status %>
            <%= f.collection_select :status_id, @statuses, :id, :name, {:include_blank => "Please select"}, class: 'form-control' %>
          </div>
          <div class="form-group col-xs-6">
            <%= f.label :date_contacted %>
            <%= f.text_field :contact_date, class: 'form-control dp-sel' %>
          </div>
        </div>
        <div class="row">
          <div class="form-group col-xs-6">
            <%= f.label :team %>
            <%= f.collection_select :team_id, @teams, :id, :members, {:include_blank => "Please select"}, class: 'form-control' %>
          </div>
          <div class="form-group col-xs-6">
            <%= f.label :tshirt_size %>
            <%= f.select(:tshirt_size, @tshirts, {}, { :class => 'form-control' }) %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :why %>
          <%= f.text_area :why, :rows => 5, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.submit class: 'btn btn-primary' %>
          <%= (link_to 'Delete Hacker', @hacker, method: :delete, data: {confirm: "Are you sure?"} , class: 'btn btn-danger') if params[:action] == 'edit' %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/hackers/commited.html.erb
<div class="index-carousel">
  <div class="carousel-images">
    <div class="carousel-item index-carousel-item mlb-victis active">
      <div class="index-carousel-item-wrapper">
        <section class="index-carousel-content2">
          <%= form_for @hacker, as: :hacker, url: "update_commit/#{@hacker.id}", method: :update_commit do |f| %>
          <%# <%= form_for(@hacker) do |f| %1> %>
            <div class="panel panel-default">
              <div class="panel-heading">
                <% if @hacker.status.name != 'Commited' %>
                  <h3>Complete the form below and click Commit to confirm your attendance.</h3>
                <% else %>
                  <h3>You have commited to attend BoilerMake!</h3>
                <% end %>
              </div>
              <div class="panel-body">

                <% if notice %>
                  <p class="alert alert-success"><%= notice %></p>
                <% end %>
                <% if alert %>
                  <p class="alert alert-danger"><%= alert %></p>
                <% end %>

                <div class="form">
                  <div class="row">
                    <div class="form-group col-xs-6">
                      <%= f.label :First, "First Name" %>
                      <%= f.text_field :fname, class: 'form-control' %>
                    </div>
                    <div class="form-group col-xs-6">
                      <%= f.label :Last, "Last Name" %>
                      <%= f.text_field :lname, class: 'form-control' %>
                    </div>
                  </div>
                  <div class="row">
                    <div class="form-group col-xs-6">
                      <%= f.label :tshirt_size, "T-Shirt Size" %>
                      <%= f.select(:tshirt_size, @tshirts, {}, { :class => 'form-control' }) %>
                    </div>
                    <div class="form-group col-xs-6">
                      <%= f.label :github, "Github URL" %>
                      <%= f.text_field :github, class: 'form-control' %>
                    </div>
                  </div>
                  <div class="form-group">
                    <%= f.label :resume %>
                    <% if @hacker.resume.url == '/resumes/original/missing.png' %>
                      <%= f.file_field :resume, :required => true %>
                    <% else %>
                      <%= f.file_field :resume %>
                    <% end %>                    
                  </div>
                  <% if @hacker.resume_content_type == 'application/pdf' || @hacker.resume_content_type == 'application/vnd.openxmlformats-officedocument.wordprocessingml.document' || @hacker.resume_content_type == 'application/msword' %>
                    <div class="form-group">
                      <%= link_to 'View your uploaded resume', @hacker.resume.url %>
                    </div>
                  <% end %>
                  <div class="form-group">
                    <%= f.submit "Commit", class: 'btn btn-primary' %>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </section>
        <div class="index-carousel-overlay"></div>
        <div class="index-carousel-background">
          <%= image_tag("corec2.jpg") %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/hackers/committed.html.erb
<div class="index-carousel">
  <div class="carousel-images">
    <div class="carousel-item index-carousel-item mlb-victis active">
      <div class="index-carousel-item-wrapper">
        <section class="index-carousel-content2">
          <%= form_for @hacker, as: :hacker, url: "update_commit/#{@hacker.id}", method: :update_commit do |f| %>
          <%# <%= form_for(@hacker) do |f| %1> %>
            <div class="panel panel-default">
              <div class="panel-heading">
                <% if @hacker.status.name != 'Committed' %>
                  <h3>Complete the form below and click Commit to confirm your attendance.</h3>
                <% else %>
                  <h3>You have committed to attend BoilerMake!</h3>
                <% end %>
              </div>
              <div class="panel-body">

                <% if notice %>
                  <p class="alert alert-success"><%= notice %></p>
                <% end %>
                <% if alert %>
                  <p class="alert alert-danger"><%= alert %></p>
                <% end %>

                <div class="form">
                  <div class="row">
                    <div class="form-group col-xs-6">
                      <%= f.label :First, "First Name" %>
                      <%= f.text_field :fname, class: 'form-control', required: true %>
                    </div>
                    <div class="form-group col-xs-6">
                      <%= f.label :Last, "Last Name" %>
                      <%= f.text_field :lname, class: 'form-control', required: true %>
                    </div>
                  </div>
                  <div class="row">
                    <div class="form-group col-xs-6">
                      <%= f.label :tshirt_size, "T-Shirt Size" %>
                      <%= f.select(:tshirt_size, @tshirts, {}, { :class => 'form-control' }) %>
                    </div>
                    <div class="form-group col-xs-6">
                      <%= f.label :github, "Github URL" %>
                      <%= f.text_field :github, class: 'form-control' %>
                    </div>
                  </div>
                  <div class="row">
                    <div class="form-group col-xs-6">
                      <%= f.label :cell, "Cell Phone" %>
                      <%= f.text_field :cell, :required => true, class: 'form-control' %>
                    </div>
                    <div class="form-group col-xs-6">
                        <%= f.label :resume %>
                        <% if @hacker.resume.url == '/resumes/original/missing.png' %>
                          <%= f.file_field :resume, :required => true %>
                        <% else %>
                          <%= f.file_field :resume %>
                        <% end %>     
                    </div>
                  </div>
                  <div class="row">
                    <div class="form-group col-xs-6">
                      <div class="checkbox">
                        <label>
                          <input type="checkbox" required="required"> I agree to <a href="https://dl.dropboxusercontent.com/u/22196024/BoilerMake-Waiver.pdf">BoilerMake's Terms.</a>
                        </label>
                      </div>
                      <div class="checkbox">
                        <label>
                          <input type="checkbox" required="required"> I am 18 years or older.
                        </label>
                      </div>
                    </div>
                  </div>
                  <% if @hacker.resume_content_type == 'application/pdf' || @hacker.resume_content_type == 'application/vnd.openxmlformats-officedocument.wordprocessingml.document' || @hacker.resume_content_type == 'application/msword' %>
                    <div class="form-group">
                      <%= link_to 'View your uploaded resume', @hacker.resume.url %>
                    </div>
                  <% end %>
                  <div class="form-group">
                    <%= f.submit "Commit", class: 'btn btn-primary' %>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </section>
        <div class="index-carousel-overlay"></div>
        <div class="index-carousel-background">
          <%= image_tag("corec2.jpg") %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/hackers/edit.html.erb
<%= render 'form' %>

app/views/hackers/index.html.erb
<h1>
  Hackers
  <% if can? :create, @hackers %>
    <%= link_to 'New Hacker', new_hacker_path, class: 'btn btn-primary' %>
  <% end %>

</h1>

<table class="table table-striped hacker-table">
  <thead>
    <tr>
      <% if can? :index, :hackers, :status %>
        <th><%= sortable "status_id" %></th>
      <% end %>
      <% if can? :index, :hackers, :rating %>
        <th><%= sortable "rating" %></th>
      <% else %>
        <th><%= sortable "email" %></th>
      <% end %>
      <th><%= sortable "fname", "First Name" %></th>
      <th><%= sortable "lname", "Last Name" %></th>
      <th><%= sortable "school_id" %></th>
      <% if can? :index, :hackers, :github %>
        <th><%= sortable "github" %></th>
      <% else %>
        <th><%= sortable "cell" %></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @hackers.each do |hacker| %>
      <tr class="clickable pointer" href="<%= hacker_path(hacker) %>">
        <% if can? :index, :hackers, :status %>
          <td><%= hacker.status.name if hacker.status %></td>
        <% end %>
        <% if can? :index, :hackers, :rating %>
          <td><%= '%.2f' % hacker.rating if hacker.rating %></td>
        <% else %>
          <td><%= hacker.email.downcase %></td>
        <% end %>
        <td><%= hacker.fname.capitalize %></td>
        <td><%= hacker.lname.capitalize %></td>
        <td><%= hacker.school.name if hacker.school %></td>
        <% if can? :index, :hackers, :github %>
          <td><%= link_to hacker.github.downcase, "http://github.com/#{hacker.github}"%></td>
        <% else %>
          <td><%= hacker.cell %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="center">
  <%= will_paginate @hackers, renderer: BootstrapPagination::Rails %>
</div>

app/views/hackers/new.html.erb
<h1>New hacker</h1>
<%= render 'form' %>
<%= link_to 'Back', hackers_path %>

app/views/hackers/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h1><%= @hacker.fname + ' ' + @hacker.lname %></h1>
  </div>
  <ul class="list-group">
    <% if can? :show, :hackers, :status %>
      <li class="list-group-item">
        <strong>Status:</strong>
        <%= @hacker.status.name if @hacker.status %>
      </li>
    <% end %>

    <% if can? :show, :hackers, :contact_date %>
      <li class="list-group-item">
        <strong>Date Contacted:</strong>
        <%= @hacker.contact_date %>
      </li>
    <% end %>

    <% if can? :show, :hackers, :rating %>
      <li class="list-group-item">
        <strong>Rating:</strong>
        <%= @hacker.rating %>
      </li>
    <% end %>

    <li class="list-group-item">
      <strong>School:</strong>
      <%= school_link @hacker.school.name %>
    </li>

    <% if can? :show, :hackers, :team %>
      <li class="list-group-item">
        <strong><%= link_to 'Team:', @hacker.team %></strong>
        <%= @teammates %>
      </li>
    <% end %>

    <% if can? :show, :hackers, :rating_avg %>
      <li class="list-group-item">
        <strong>Team Rating:</strong>
        <%= @hacker.team.rating_avg %>
      </li>
    <% end %>

    <li class="list-group-item">
      <strong>Email:</strong>
      <%= mail_to @hacker.email %>
    </li>

    <% if can? :show, :hackers, :github %>
      <li class="list-group-item">
        <strong>Github:</strong>
        <% unless @hacker.github.empty? %>
          <%= link_to @hacker.github, 'http://www.github.com/' + @hacker.github %>
        <% else %>
          This hacker doesn't have a github :(
        <% end %>
      </li>
    <% end %>

    <% if can? :show, :hackers, :tshirt_size %>
      <li class="list-group-item">
        <strong>Tshirt size:</strong>
        <%= @hacker.tshirt_size %>
      </li>
    <% end %>

    <% if can? :show, :hackers, :cell %>
      <li class="list-group-item">
        <strong>Cell Phone:</strong>
        <%= @hacker.cell %>
      </li>
    <% end %>

    <% if can? :show, :hackers, :why %>
      <li class="list-group-item">
        <strong>Why:</strong>
        <%= @hacker.why %>
      </li>
    <% end %>

    <% if can? :show, :hackers, :resume %>
      <li class="list-group-item">
        <strong>Resume:</strong>
        <% if @hacker.resume.url != '/resumes/original/missing.png' %>
          <%= link_to @hacker.resume_file_name, @hacker.resume.url %>
        <% else %>
          This hacker does not have a resume.
        <% end %>
      </li>
    <% end %>
  </ul>
</div>
<div>
  <%= link_to 'Back', hackers_path, class: 'btn btn-primary' %>
  <% if can? :update, @hacker %>
    <%= link_to 'Edit', edit_hacker_path(@hacker), class: 'btn btn-primary' %>
  <% end %>
</div>