config/routes.rb
HackathonTeams::Application.routes.draw do
  root 'pages#root'

  resources :representatives
  resources :sponsors
  resources :teams
  resources :schools
  resources :hackers

  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}

  get 'committed' => 'hackers#committed'

  post 'update_commit/:id' => 'hackers#update_commit'

  get 'stats' => 'stats#index'
end

app/models/representative.rb
class Representative < ActiveRecord::Base
  belongs_to :sponsor
end

app/controllers/representatives_controller.rb
class RepresentativesController < ApplicationController
  before_action :set_representative, only: [:show, :edit, :update, :destroy]
  before_action :set_sponsors

  # GET /representatives
  # GET /representatives.json
  def index
    @representatives = Representative.all
  end

  # GET /representatives/1
  # GET /representatives/1.json
  def show
  end

  # GET /representatives/new
  def new
    @representative = Representative.new
  end

  # GET /representatives/1/edit
  def edit
  end

  # POST /representatives
  # POST /representatives.json
  def create
    @representative = Representative.new(representative_params)

    respond_to do |format|
      if @representative.save
        format.html { redirect_to @representative, notice: 'Representative was successfully created.' }
        format.json { render action: 'show', status: :created, location: @representative }
      else
        format.html { render action: 'new' }
        format.json { render json: @representative.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /representatives/1
  # PATCH/PUT /representatives/1.json
  def update
    respond_to do |format|
      if @representative.update(representative_params)
        format.html { redirect_to @representative, notice: 'Representative was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @representative.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /representatives/1
  # DELETE /representatives/1.json
  def destroy
    @representative.destroy
    respond_to do |format|
      format.html { redirect_to representatives_url }
      format.json { head :no_content }
    end
  end

  private
    # Set sponsors to be used for actions
    def set_sponsors
      @sponsors = Sponsor.all
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_representative
      @representative = Representative.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def representative_params
      params.require(:representative).permit(:fname, :lname, :title, :email,
                                             :sponsor, :sponsor_id, :cell)
    end
end

app/helpers/representatives_helper.rb
module RepresentativesHelper
end

app/views/representatives/_form.html.erb
<%= form_for(@representative) do |f| %>
  <% if @representative.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@representative.errors.count, "error") %> prohibited this representative from being saved:</h2>

      <ul>
      <% @representative.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-4">
      <div class="form">
        <div class="panel panel-default">
          <div class="panel-body">
            <div class="form-group">
              <%= f.label 'Sponsor' %><br>
              <%= f.collection_select :sponsor_id, @sponsors, :id, :company_name, {:include_blank => "Sponsor"}, {class: 'form-control'} %>  
            </div>
            <div class="form-group">
              <%= f.label 'First Name' %><br>
              <%= f.text_field :fname, class: 'form-control' %>
            </div>
            <div class="form-group">
              <%= f.label 'Last Name' %><br>
              <%= f.text_field :lname, class: 'form-control' %>
            </div>
            <div class="form-group">
              <%= f.label :title %><br>
              <%= f.text_field :title, class: 'form-control' %>
            </div>
            <div class="form-group">
              <%= f.label :email %><br>
              <%= f.text_field :email, class: 'form-control' %>
            </div>
            <div class="form-group">
              <%= f.label :cell %><br>
              <%= f.text_field :cell, class: 'form-control' %>
            </div>
            <div class="actions">
              <%= f.submit class: 'btn btn-primary'%>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/representatives/edit.html.erb
<h1>Editing representative</h1>

<%= render 'form' %>

<%= link_to 'Show', @representative %> |
<%= link_to 'Back', representatives_path %>

app/views/representatives/index.html.erb
<h1>
  Representatives
  <%= link_to new_representative_path, class: 'btn btn-primary' do %>
    New Representative
  <% end %>
</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Email</th>
      <th>Company</th>
      <th>Cell</th>
    </tr>
  </thead>

  <tbody>
    <% @representatives.each do |representative| %>
      <tr class="clickable pointer" href="<%= representative_path(representative) %>">
        <td><%= representative.fname %></td>
        <td><%= representative.lname %></td>
        <td><%= representative.email %></td>
        <td><%= representative.sponsor.company_name if representative.sponsor %></td>
        <td><%= representative.cell %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/representatives/new.html.erb
<h1>New Representative</h1>

<%= render 'form' %>

<%= link_to 'Back', representatives_path %>

app/views/representatives/show.html.erb
<p id="notice"><%= notice %></p>

<div class="panel panel-default">
  <div class="panel-heading">
    <h1><%= @representative.fname + ' ' + @representative.lname %></h1>
  </div>
  <ul class="list-group">
    <li class="list-group-item">
		  <strong>First Name:</strong>
		  <%= @representative.fname %>
		</li>

		<li class="list-group-item">
		  <strong>Last Name:</strong>
		  <%= @representative.lname %>
		</li>

		<li class="list-group-item">
		  <strong>Title:</strong>
		  <%= @representative.title %>
		</li>

		<li class="list-group-item">
		  <strong>Email:</strong>
		  <%= @representative.email %>
		</li>

		<li class="list-group-item">
		  <strong>Cell:</strong>
		  <%= @representative.cell %>
		</li>

		<li class="list-group-item">
			<strong>Sponsor:</strong>
			<%= link_to @representative.sponsor.company_name, sponsor_path(@representative.sponsor) %>
		</li>
	</ul>
</div>

<%= link_to 'Edit', edit_representative_path(@representative) %> |
<%= link_to 'Back', representatives_path %>