config/routes.rb
HackathonTeams::Application.routes.draw do
  root 'pages#root'

  resources :representatives
  resources :sponsors
  resources :teams
  resources :schools
  resources :hackers

  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}

  get 'committed' => 'hackers#committed'

  post 'update_commit/:id' => 'hackers#update_commit'

  get 'stats' => 'stats#index'
end

app/models/school.rb
class School < ActiveRecord::Base
  has_many :hackers

  validates :name, presence: true, uniqueness: true
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_school, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  enable_authorization do |exception|
      redirect_to hackers_path, :notice => exception.message
  end
  helper_method :sort_column, :sort_direction

  # GET /schools
  # GET /schools.json
  def index
    if params[:sort] == 'count'
      @schools = School.accessible_by(current_ability)
                       .joins(:hackers)
                       .group('schools.name')
                       .order("count(hackers.id) #{sort_direction}")
    else
      @schools = School.accessible_by(current_ability)
                       .order("#{sort_column} #{sort_direction}")
    end
  end

  # GET /schools/1
  # GET /schools/1.json
  def show
  end

  # GET /schools/new
  def new
    @school = School.new
  end

  # GET /schools/1/edit
  def edit
  end

  # POST /schools
  # POST /schools.json
  def create
    @school = School.new(school_params)

    respond_to do |format|
      if @school.save
        format.html { redirect_to @school, notice: 'School was successfully created.' }
        format.json { render action: 'show', status: :created, location: @school }
      else
        format.html { render action: 'new' }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schools/1
  # PATCH/PUT /schools/1.json
  def update
    respond_to do |format|
      if @school.update(school_params)
        format.html { redirect_to @school, notice: 'School was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schools/1
  # DELETE /schools/1.json
  def destroy
    @school.destroy
    respond_to do |format|
      format.html { redirect_to schools_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_school
      @school = School.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def school_params
      params.require(:school).permit(:name)
    end

    def sort_column
      School.column_names.include?(params[:sort]) ? params[:sort] : "id"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/schools/_form.html.erb
<%= form_for(@school) do |f| %>
  <% if @school.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@school.errors.count, "error") %> prohibited this school from being saved:</h2>

      <ul>
      <% @school.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="panel panel-default">
    <div class="form">
      <div class="panel-body">
        <div class="form-group">
          <%= f.label :name %><br>
          <%= f.text_field :name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.submit class: 'btn btn-primary' %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/schools/edit.html.erb
<h1>Editing school</h1>

<%= render 'form' %>

<%= link_to 'Show', @school %> |
<%= link_to 'Back', schools_path %>

app/views/schools/index.html.erb
<h1>
  Schools
  <% if can? :create, @schools %>
    <%= link_to 'New School', new_school_path, class: 'btn btn-primary' %>
  <% end %>
</h1>

<table class="table table-striped" id="clickable">
  <thead>
    <tr>
      <th><%= sortable "name" %></th>
      <th><%= sortable_count "count" %></th>
    </tr>
  </thead>

  <tbody>
    <% c = Status.where('name = ?','Committed').first.id %>
    <% @schools.each do |school| %>
      <tr class="clickable pointer" href="<%= school_path(school) %>">
        <td><%= school.name %></td>
        <td><%= school.hackers.where('status_id = ?', c).count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/schools/new.html.erb
<h1>New school</h1>

<%= render 'form' %>

<%= link_to 'Back', schools_path %>

app/views/schools/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @school.name %></h1>

<table class="table table-striped">
  <thead>
    <tr>
      <% if can? :index, :hackers, :status %>
        <th>Status</th>
      <% end %>
      <% if can? :index, :hackers, :rating %>
        <th>Rating</th>
      <% else %>
        <th>Email</th>
      <% end %>
      <th>Fname</th>
      <th>Lname</th>
      <th>Github</th>
    </tr>
  </thead>

  <tbody>
    <% @school.hackers.accessible_by(current_ability).each do |hacker| %>
      <tr class="clickable" href="<%= hacker_path(hacker) %>">
        <% if can? :index, :hackers, :status %>
          <td><%= hacker.status.name if hacker.status %></td>
        <% end %>
        <% if can? :index, :hackers, :rating %>
          <td><%= '%.2f' % hacker.rating if hacker.rating %></td>
        <% else %>
          <td><%= hacker.email.downcase %></td>
        <% end %>
        <td><%= hacker.fname.capitalize %></td>
        <td><%= hacker.lname.capitalize %></td>
        <td><%= link_to hacker.github.downcase, "http://github.com/#{hacker.github}" if hacker.github %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Back', schools_path, class: 'btn btn-primary' %>
<% if can? :update, @school %>
  <%= link_to 'Edit', edit_school_path(@school), class: 'btn btn-primary' %>
<% end %>