config/routes.rb
HackathonTeams::Application.routes.draw do
  root 'pages#root'

  resources :representatives
  resources :sponsors
  resources :teams
  resources :schools
  resources :hackers

  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}

  get 'committed' => 'hackers#committed'

  post 'update_commit/:id' => 'hackers#update_commit'

  get 'stats' => 'stats#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user

    can [:commit, :committed, :update_commit], :hackers

    if user.role? :super_admin
      can :access, :all
    elsif user.role? :admin
      can [:index, :show], :all
    elsif user.role? :sponsor
      can [:index, :show], :hackers, :status => Status.where("name = 'Committed'").first
      can [:index, :show], :schools, :name => ['Allegheny College',
      'Carnegie Mellon University','DePauw university','Northwestern University',
      'Ohio State University','Ohio University','Penn State University',
      'Purdue University','Rose-Hulman Institute of Technology','Rutgers University',
      'UIUC','University at Buffalo','University of Cincinnati','University of Iowa',
      'University of Maryland','University of Michigan','University of Pittsburgh',
      'University of Waterloo','University of Wisconsin - Madison']
      cannot [:index, :show], :hackers, [:status, :rating, :contact_date,
                                         :team, :rating_avg, :cell,
                                         :tshirt_size, :why]
    elsif user.role? :representative
      cannot :access, [:teams, :stats, :schools]
      can [:index, :show], :hackers,
                           :status_id => Status.where("name = 'Committed'
                                                      OR name = 'Accepted'
                                                      OR name = 'Waitlisted'").map {|s| s.id},
                           :school => School.find(user.school_id)
      cannot [:index, :show], :hackers, [:rating, :github, :contact_date,
                                         :team, :rating_avg, :tshirt_size,
                                         :why, :resume]
    end
  end
end

app/models/hacker.rb
class Hacker < ActiveRecord::Base
  belongs_to :school
  belongs_to :team
  belongs_to :status
  has_many :ratings

  has_attached_file :resume,
    :storage => :s3,
    :s3_credentials => {
      :bucket => ENV['AWS_BUCKET'],
      :access_key_id => ENV['AWS_ACCESS_KEY_ID'],
      :secret_access_key => ENV['AWS_SECRET_ACCESS_KEY']
    }
  validates_format_of :resume_file_name,
                      :with => %r{\.(docx|doc|pdf)\z}i,
                      :allow_blank => true
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :hacker
end

app/models/representative.rb
class Representative < ActiveRecord::Base
  belongs_to :sponsor
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users
end

app/models/school.rb
class School < ActiveRecord::Base
  has_many :hackers

  validates :name, presence: true, uniqueness: true
end

app/models/sponsor.rb
class Sponsor < ActiveRecord::Base
  has_many :representatives
end

app/models/stat.rb
class Stat < ActiveRecord::Base
end

app/models/status.rb
class Status < ActiveRecord::Base
  has_many :hackers
end

app/models/team.rb
class Team < ActiveRecord::Base
  has_many :hackers
  def members
    if self.hackers.present?
      return self.hackers.map{ |hacker| hacker.fname + ' ' + hacker.lname if hacker.lname }.join(', ')
    else
      return self.id.to_s
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable,
         :rememberable, :trackable, :validatable
  has_and_belongs_to_many :roles

  def role?(role)
    self.roles.find_by_name(role.to_s)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def root
  end

  def welcome
  end
end

app/controllers/stats_controller.rb
class StatsController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource
  enable_authorization do |exception|
      redirect_to hackers_path, :alert => exception.message
  end

  def index

    @schools = ['Purdue University','UIUC','University of Wisconsin - Madison',
                'Rutgers University','Carnegie Mellon University',
                'Ohio State University','University of Maryland',
                'University of Waterloo','University of Michigan',
                'Rose-Hulman Institute of Technology','Northwestern University',
                'University of Iowa']

    @applied = Hash.new
    @accepted = Hash.new;
    @waitlisted = Hash.new;
    @rejected = Hash.new;
    @committed = Hash.new;
    @declined = Hash.new;

    accepted_id = Status.find_by_name('Accepted').id
    waitlisted_id = Status.find_by_name('Waitlisted').id
    rejected_id = Status.find_by_name('Rejected').id
    committed_id = Status.find_by_name('Committed').id
    declined_id = Status.find_by_name('Declined').id

    @schools.each do |school|
      s = School.find_by_name(school)
      @applied[school] = s.hackers.count
      @accepted[school] = s.hackers.where("status_id = #{accepted_id}").count
      @waitlisted[school] = s.hackers.where("status_id = #{waitlisted_id}").count
      @rejected[school] = s.hackers.where("status_id = #{rejected_id}").count
      @committed[school] = s.hackers.where("status_id = #{committed_id}").count
      @declined[school] = s.hackers.where("status_id = #{declined_id}").count
    end

    @total = Hash.new
    @total[:applied] = Hacker.all.count
    @total[:accepted] = Hacker.where("status_id = #{accepted_id}").count
    @total[:waitlisted] = Hacker.where("status_id = #{waitlisted_id}").count
    @total[:rejected] = Hacker.where("status_id = #{rejected_id}").count
    @total[:committed] = Hacker.where("status_id = #{committed_id}").count
    @total[:declined] = Hacker.where("status_id = #{declined_id}").count

    @other = Hash.new
    @other[:applied] = @total[:applied] - @applied.each_value.inject(:+)
    @other[:accepted] = @total[:accepted] - @accepted.each_value.inject(:+)
    @other[:waitlisted] = @total[:waitlisted] - @waitlisted.each_value.inject(:+)
    @other[:rejected] = @total[:rejected] - @rejected.each_value.inject(:+)
    @other[:committed] = @total[:committed] - @committed.each_value.inject(:+)
    @other[:declined] = @total[:declined] - @declined.each_value.inject(:+)

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    direction = column == sort_column && sort_direction == 'asc' ? 'desc' : 'asc'
    link_to title, :sort => column, :direction => direction
  end

  def sortable_count(column, title = nil)
    title ||= column.titleize
    direction = column == "count" && sort_direction == 'asc' ? 'desc' : 'asc'
    link_to title, :sort => column, :direction => direction
  end

  # def sortable_count(title)
  #   direction = column == sort_column && sort_direction == 'asc' ? 'desc' : 'asc'
  #   link_to title, :sort => column, :direction => direction
  # end

  def school_link(name)
    school = School.find_by_name(name)
    link_to name, school
  end
end

app/helpers/hackers_helper.rb
module HackersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/sponsors_helper.rb
module SponsorsHelper
end

app/helpers/stats_helper.rb
module StatsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/layouts/_header.html.erb
<div class="navbar navbar-default" role="navigation">
  <div class="container">
    <ul class="nav navbar-nav navbar-right">
      <%# <li><%= current_user.try(:email) %1></li> %>
      <% if can? :index, :stats %>
        <li><%= link_to 'Stats', stats_path %></li>
      <% end %>
      <% if can? :index, :hackers %>
        <li><%= link_to 'Hackers', hackers_path %></li>
      <% end %>
      <% if can? :index, :teams %>
        <li><%= link_to 'Teams', teams_path %></li>
      <% end %>
      <% if can? :index, :schools %>
        <li><%= link_to 'Schools', schools_path %></li>
      <% end %>      
      <% if can? :index, :representatives %>
        <li><%= link_to 'Representatives', representatives_path %></li>
      <% end %>      
      <% if can? :index, :sponsors %>
        <li><%= link_to 'Sponsors', sponsors_path %></li>
      <% end %>
      <% if user_signed_in? %>
        <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to 'Signin', new_user_session_path %></li>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>HackathonTeams</title>
<meta content='width=device-width, initial-scale=1.0, user-scalable=no' name='viewport'>
<%= stylesheet_link_tag    "application", media: "all" %>
<%= javascript_include_tag "application" %>
<%= csrf_meta_tags %>
</head>
<body>
  <%= render :partial => 'layouts/header' unless params[:action] == 'commit' || params[:action] == 'committed' %>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert alert-info") %>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/pages/_welcome.html.erb
<h1>Welcome, BoilerMake <%= current_user.roles.first.name.capitalize %></h1>
<div class="welcome-hero">
  <h3>Use this area to browse hackers.</h3>
  <h3>If you have any questions, problems, or comments email
      <a href='<%= t :director_email%>'><%= t :current_director%></a>.
  </h3>
</div>

app/views/pages/root.html.erb
<% if user_signed_in? %>
  <%= render 'welcome' %>
<% else %>
  <%= render 'hackers/commit' %>
<% end %>